name: check for drift
description: This action checks for drift
runs:
    using: "composite"
    steps:
        - name: check for drift
          run: ${{ github.action_path }}/check_for_drift.sh
          shell: bash
        