name: check for drift
description: This action checks for drift
runs:
    using: "composite"
    steps:
        - name: check for drift
          run: check_for_drift.sh
          shell: bash
        