name: write comment
description: 'Writes a comment on the pull request'
inputs:
  custom_plan_location:
    description: 'The location of the plan output file'
    required: true
  custom_body_message:
    description: 'The message to be input into the body'
    required: true
  comment_marker:
    description: 'identifier for comments to prevent spam in pr'
    required: true

runs:
  using: "composite"
  steps:
    - name: write comment
      run: ${{ github.action_path }}/write_comment.sh
      shell: bash
      env:
        client_repository: ${{ github.repository }}
        client_pull_request_number: ${{ github.event.pull_request.number }}
        custom_plan_location: ${{ inputs.custom_plan_location }}
        body_message_to_post: ${{ inputs.custom_body_message }}
        comment_marker: ${{ inputs.comment_marker }}
