name: drift-detection-check
run-name: Checking drift for${{ github.actor }}
on:
  workflow_call:
    inputs:
      branch:
        required: true
        type: string
      higher_branch:
        required: false
        type: string
      # iac_tool:
      #   required: true
      #   type: string
      iac_technology:
        required: true
        type: string
      lower_environment:
        required: true
        type: string
      higher_environment:
        required: true
        type: string
      run_cd_checks:
        required: true
        type: string
      cloud_provider:
        required: true
        type: string
      iac_technology_version:
        required: true
        type: string
      repo_terragrunt_version:
        required: true
        type: string
    secrets:
      cloud_token:
        required: false
      aws_region:
        required: false
      aws_account_id:
        required: false
      aws_role_to_assume:
        required: false
      
# env:
#   higher_branch: ${{ inputs.branch == 'develop' && 'main' }}
permissions:
  pull-requests: write
  contents: read 
  security-events: write 
  actions: read 
jobs:
  check_for_drift:
    runs-on: ubuntu-24.04
    steps:

      - name: checkout higher branch
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.higher_branch }}
          fetch-depth: 0      
      
      - name: authenticate to cloud provider
        uses: iac-pipeline/iac-pipeline/.github/actions/basic_setup@develop
        with:
          cloud_provider: ${{ inputs.cloud_provider }}
          iac_technology: ${{ inputs.iac_technology }}
          cloud_token_secret_name: ${{ secrets.cloud_token }}
          aws_region: ${{ secrets.aws_region }}
          aws_account_id: ${{ secrets.aws_account_id }}
          aws_role_to_assume: ${{ secrets.aws_role_to_assume }}
          iac_technology_version: ${{ inputs.iac_technology_version }}
          repo_terragrunt_version: ${{ inputs.repo_terragrunt_version }}

      
      - name: check for drift
        id: check_state_of_environment
        uses: iac-pipeline/iac-pipeline/.github/actions/drift_detection@develop
        with:
          branch: ${{ inputs.branch }}
          higher_branch: ${{ inputs.higher_branch }}
          higher_environment: ${{ inputs.higher_environment }}
          run_cd_checks: ${{ inputs.run_cd_checks }}
      
      - name: send comment to user on PR
        if: steps.check_state_of_environment.outputs.check_for_drift_outcome == 'failure'
        uses: iac-pipeline/iac-pipeline/.github/actions/write_comment@develop
        with:
          custom_plan_location: ${{ steps.check_state_of_environment.outputs.output_file_location }}
          custom_body_message: "Drift detected in module ${{ steps.check_state_of_environment.outputs.module_with_drift }}"
      
      - name: end script with failure exit code
        if: steps.check_state_of_environment.outputs.check_for_drift_outcome == 'failure'
        run: exit 1

