name: CI-software-quality-checks
run-name: Checking code quality for${{ github.actor }}
on:
  workflow_call:
    inputs:
      branch:
        required: true
        type: string
      # iac_tool:
      #   required: true
      #   type: string
      iac_technology:
        required: true
        type: string
    secrets:
      cloud_token:
        required: true
env:
  higher_branch: ${{ inputs.branch == 'develop' && 'main' }}

permissions:
  contents: read 
  security-events: write 
  actions: read 

jobs:
  call_initialise_workflow:
    uses: iac-pipeline/iac-pipeline/.github/workflows/initialise_workflow.yml@develop
    with:
      iac_technology: ${{ inputs.iac_technology }}
    id: call_initialise_workflow_job

  call_terraform_quality_checks:
    needs: call_initialise_workflow
    uses: iac-pipeline/iac-pipeline/.github/workflows/terraform_quality_checks.yml@develop
    with:
      branch: ${{ inputs.branch }}
      iac_technology: ${{ needs.call_initialise_workflow_job.outputs.iac_technology }}
      higher_branch: ${{ env.higher_branch }}
    secrets:
      cloud_token: ${{ secrets.cloud_token }}
    id: terraform-quality-checks

  call-drift-detection:
    needs: terraform-quality-checks
    uses: iac-pipeline/iac-pipeline/.github/workflows/check_for_drift.yml@develop
    with:
      branch: ${{ inputs.branch }}
      iac_technology: ${{ needs.call_initialise_workflow_job.outputs.iac_technology}}
    secrets:
      cloud_token: ${{ secrets.cloud_token }}
