name: CI-software-quality-checks
run-name: Checking code quality for ${{ github.actor }}
on:
  workflow_call:
    inputs:
      branch:
        required: true
        type: string
      # iac_tool:
      #   required: true
      #   type: string
      iac_technology:
        required: true
        type: string
    secrets:
      cloud_token:
        required: true

permissions:
  contents: read 
  security-events: write 
  actions: read 

jobs:
  initialise_workflow:
    runs-on: ubuntu-24.04
    outputs:
      iac_technology: ${{ steps.set_iac_technology.outputs.iac_technology }}
      higher_branch: ${{ steps.set_higher_branch.outputs.higher_branch }}
    steps:
      - name: set iac environment as lowercase
        run: |
          temp_iac_value="${{ inputs.iac_technology }}"
          echo "iac_technology=${temp_iac_value@L}" >> "${GITHUB_ENV}"

      - name: check iac technology is valid
        run: |
          iac_technology="${{ env.iac_technology }}"
          if [[ "$iac_technology" == "terraform" || "$iac_technology" == "opentofu" ]]; then
            echo "Utilising $iac_technology"
          else
            echo "::error ::Invalid IAC type provided, must be either terraform or opentofu"
            exit 1
          fi
      
      - name: set output for iac technology
        id: set_iac_technology
        run: echo "iac_technology=${{ env.iac_technology }}" >> "$GITHUB_OUTPUT"
      
      - name: set higher branch
        id: set_higher_branch
        run: |
          if [[ "${{ inputs.branch }}" == "develop" ]]; then
            echo "higher_branch=main" >> $GITHUB_OUTPUT
          else
            echo "higher_branch=" >> $GITHUB_OUTPUT
          fi

  call_terraform_quality_checks:
    needs: initialise_workflow
    uses: iac-pipeline/iac-pipeline/.github/workflows/terraform_quality_checks.yml@develop
    with:
      branch: ${{ inputs.branch }}
      iac_technology: ${{ needs.initialise_workflow.outputs.iac_technology }}
      higher_branch: ${{ needs.initialise_workflow.outputs.higher_branch }}
    secrets:
      cloud_token: ${{ secrets.cloud_token }}

  # call-drift-detection:
  #   needs: initialise_workflow
  #   uses: iac-pipeline/iac-pipeline/.github/workflows/check_for_drift.yml@develop
  #   with:
  #     branch: ${{ inputs.branch }}
  #     iac_technology: ${{ needs.initialise_workflow.outputs.iac_technology}}
  #   secrets:
  #     cloud_token: ${{ secrets.cloud_token }}
