name: CI-software-quality-checks
run-name: Checking code quality for ${{ github.actor }}
on:
  workflow_call:
    inputs:
      higher_branch:
        required: false
        type: string
        default: ${{ github.base_ref }}
      branch:
        required: false
        type: string
        default: ${{ github.head_ref }}
      # iac_tool:
      #   required: true
      #   type: string
      iac_technology:
        required: true
        type: string
      environments:
        required: true
        type: string
    secrets:
      cloud_token:
        required: true

permissions:
  contents: read 
  security-events: write 
  actions: read 

jobs:
  #Define the variables for the workflow
  initialise_workflow:
    runs-on: ubuntu-24.04
    outputs:
      iac_technology: ${{ steps.set_iac_technology.outputs.iac_technology }}
      lower_environment: ${{ steps.set_environment_values.outputs.lower_environment }}
      higher_environment: ${{ steps.set_environment_values.outputs.higher_environment }}
      run_cd_checks: ${{ steps.step_register_to_run_ci_or_cd.outputs.run_cd_checks }}
    steps:

      - name: check to run ci or cd
        id: step_register_to_run_ci_or_cd
        run: |
          echo "checking to run ci or cd"
          if [ ${{ github.event.pull_request.merged }} == true ]; then
            echo "This is a merged pull request, running CD checks"
            echo "run_cd_checks=true" >> "${GITHUB_OUTPUT}"
          else
            echo "This is not a merged pull request, running CI checks"
            echo "run_cd_checks=false" >> "${GITHUB_OUTPUT}"
          fi
          
      - name: install yaml2json
        run: |
          set -ex
          sudo apt install yaml2json

      - name: show inputs
        run: |
          set -ex 
          echo "Branch: ${{ inputs.branch }}"
          echo "IAC Technology: ${{ inputs.iac_technology }}"
          echo "Standard Branch: ${{ inputs.branch }}"
          echo "Higher Branch: ${{ inputs.higher_branch }}"
          echo "Environments: ${{ inputs.environments }}"
      
      - name: set environment values
        id: set_environment_values
        run: |
          input_json="$(echo "${{ inputs.environments}}" | yaml2json)"
          echo "lower_environment=$(echo $input_json | jq -r --arg branch "${{ inputs.branch }}" '.[$branch]')" >> "${GITHUB_OUTPUT}"
          echo "higher_environment=$(echo $input_json | jq -r --arg branch "${{ inputs.higher_branch }}" '.[$branch]')" >> "${GITHUB_OUTPUT}"

      - name: set iac environment as lowercase
        run: |
          temp_iac_value="${{ inputs.iac_technology }}"
          echo "iac_technology=${temp_iac_value@L}" >> "${GITHUB_ENV}"
        #ignore linter for env.iac_technology, it is defined in the echo statement
      - name: check iac technology is valid
        run: |
          iac_technology="${{ env.iac_technology }}"
          if [[ "$iac_technology" == "terraform" || "$iac_technology" == "opentofu" ]]; then
            echo "Utilising $iac_technology"
          else
            echo "::error ::Invalid IAC type provided, must be either terraform or opentofu"
            exit 1
          fi
      
      - name: set output for iac technology
        id: set_iac_technology
        run: echo "iac_technology=${{ env.iac_technology }}" >> "$GITHUB_OUTPUT"

  ##### ci steps #####
  call_terraform_quality_checks:
    needs: initialise_workflow
    if: needs.initialise_workflow.outputs.run_cd_checks == 'false'
    uses: iac-pipeline/iac-pipeline/.github/workflows/terraform_quality_checks.yml@develop
    with:
      branch: ${{ inputs.branch }}
      iac_technology: ${{ needs.initialise_workflow.outputs.iac_technology }}
      higher_branch: ${{ inputs.higher_branch }}
    secrets:
      cloud_token: ${{ secrets.cloud_token }}

  call-drift-detection:
    needs: initialise_workflow
    uses: iac-pipeline/iac-pipeline/.github/workflows/check_for_drift.yml@develop
    with:
      branch: ${{ inputs.branch }}
      higher_branch: ${{ inputs.higher_branch }}
      iac_technology: ${{ needs.initialise_workflow.outputs.iac_technology}}
      lower_environment: ${{ needs.initialise_workflow.outputs.lower_environment }}
      higher_environment: ${{ needs.initialise_workflow.outputs.higher_environment }}
    secrets:
      cloud_token: ${{ secrets.cloud_token }}
  ##### end of ci steps #####

  ##### cd steps #####
  call-apply:
    needs: initialise_workflow
    if: needs.initialise_workflow.outputs.run_cd_checks == 'true'
    uses: iac-pipeline/iac-pipeline/.github/workflows/apply_iac.yml@develop
    with:
      production_branch: ${{ inputs.higher_branch }}
      production_environment: ${{ needs.initialise_workflow.outputs.higher_environment }}
    secrets:
      cloud_token: ${{ secrets.cloud_token }}

    

  ### end of cd steps #####